### ISSUE TITLE
Error creating Transaction...

### ISSUE THREAD

**Issue by geopayme** [shayanb/Bitcoin-PoS-PHP#1]
Hello,

I have setup your btc pos just as you describe, but I get this error:

"There was an error creating the transaction. Please go back and try again."

Any thoughts as to why?

Here is the demo setup http://128.199.48.7/gpos/

**Comment by shayanb** [comment]
you need to give write permission on t_data/ directory within gpos. the script tries to write transaction data in the directory and fails to do so. https://github.com/shayanb/Bitcoin-PoS-PHP/blob/b7d74bb325e072ff1a93fa4eb8d65c9695dab145/sci/process-order.php#L69

**Comment by geopayme** [comment]
ok, I can understand that, but I can't see a t_data (DIR) anywhere what am I missing?

Thanks for the reply and assistance!

**Comment by geopayme** [comment]
I created a t_data (dir) under the sci(path) --> sci/t_data - it seems that I have some files in the directory now, but my next step when I submit I get the error below.

![pos1](https://cloud.githubusercontent.com/assets/8299759/7205738/17428e68-e534-11e4-9bab-60052d9ca47f.jpg)

![error1](https://cloud.githubusercontent.com/assets/8299759/7205724/f867c544-e533-11e4-9b76-1ae52ed85938.jpg)

![reports](https://cloud.githubusercontent.com/assets/8299759/7205828/b0879780-e534-11e4-9732-59a1121c8f83.jpg)

**Comment by geopayme** [comment]
The incomplete transactions seem to be fixed since the t_data [dir] was cmod() 777.
