### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by geopayme** [shayanb/Bitcoin-PoS-PHP#6]
How are the values in the altcoins.lib.php are derived?

If I wanted to add the DOGE coin or other coins...

**Comment by shayanb** [comment]
These are the default address prefixes used in each altcoins, for dogecoin you add this to the list. although the functionality with these altcoins have not been tested.
and Also this list does not contain P2SH (pay to script hash) addresses such as multisig addresses.

```
class dogecoin extends bitcoin {
  public static $address_version = "1e"; 
  public static $privkey_version = "9e"; 
}
```

**Comment by geopayme** [comment]
Thanks for the reply, my involvement with bitcoin development has been since late summer of 2014, so there is much to learn... since I came back to development.

I found this link... I suppose its a good place to review https://github.com/Bit-Wasp/multisig for multisig wallets and P2SH.

**Comment by geopayme** [comment]
So progress on the POS

http://pos.btcpays.me/gpos - your thoughts!

**Comment by shayanb** [comment]
@geopayme it looks good, UI for sure need some touches, not really my expertise... :)

regarding p2sh, multisig is a must for secure implementation but needs more standardization, I had some basic issues like if you change the order of public keys, the resulting address (that starts with 3) would be different. but I finally did some multisig transactions with Pycoin, there's a lot to do in multisig.

**Comment by geopayme** [comment]
@shayanb here is an update on the POS work...

http://pos.btcpays.me/gpos3

All coins work and value is calculated properly...

Do you know where I can get the key pairs for BTC/LTC/DOGE testnet? - silly question ->still a newbie on crypto.

FYI: I want to build a process to be able to send coins out of the wallets... but not questions yet!!!! :) If you can share any thoughts!

Also can you tell me what this does and why encode it?   $item = htmlentities(urlencode('Aunja')); 

Cheers!

**Comment by geopayme** [comment]
I have a question... did this code ever work to confirm 1 confirmation BTC transactions?

Any thoughts?

**Comment by shayanb** [comment]
@geopayme I checked your update, on the UI level (also calculating the amount) it only calculates for BTC and reflect that on the other coins, let's say something that is worth 0.12 BTC would be changed to 0.12 LTC if you change the payment method.

for the key pairs you have to search or calculate them from their protocol. most of them are available in bitcore or bitcoinjs library in networks.js I guess.

For the send coins functionality, it would be a great idea. you can get the rsa private key in the browser, use it to decrypt the private keys and sign the transaction, the most secure way would be to use bitcore or bitcoinjs to do all the signing and making the transaction on the browser, so the private keys never leave the clients browser. try this for a bit to get the hold of how this is possible : http://bitcore.io/playground/#/transaction

as for $item = htmlentities(urlencode('Aunja')) I really can't remember why... maybe I was using UTF-8 characters before that.

**Comment by shayanb** [comment]
oh and also yes it has always worked for 1 confirmation (if the browser is still open and can do jquery to see if the transaction is confirmed from blockchain.info api).
but the way you asked it, my take is that it is somehow broken, and it's possible cause I was trying to make it work on 0-confirmation and might have broken the code.
those part should be identical to how [Bitcoin SCI](http://bitfreak.info/?page=tools&t=bitsci) is coded, all the changes to confirmations are to try to make it work for 0-confirmation.

**Comment by geopayme** [comment]
This is an updated  version...

http://pos.btcpays.me/1070/

When the merchant selects LTC/DOGE/START the value on QR is the related coin. Even thought the initial display was BTC - It took me several days to work out a reasonable formula and the API to give me the values.

I had to create a simple API to extract the values http://pos.btcpays.me/rates/coin.php?pair=ltc_btc

I am sure as we learn and continue to develop this idea as part of Geopay, we'll get better at it.

The sending coin option idea is something to think about. But I have few out of the box ideas that will avoid having to send coins directly but swipe the wallets in Block.io and within geopay's user account send to any selected wallet. Idea still in progress... in partnership with Block.IO (when I ask them... :)

Atif @Nazir  the CEO is very friendly and open to new ideas...

We managed to get the 0-transaction confirmation this code on another project. But we are still working it with this project. I want to make sure all things work prior to breaking things :)

listen = ->
  setTimeout(listen, 10000)

  unless g.blockchain and g.blockchain.readyState is 1
    g.blockchain = new WebSocket("wss://ws.blockchain.info/inv")

```
g.blockchain.onopen = -> 
  $('#connection').fadeIn().removeClass('glyphicon-exclamation-sign').addClass('glyphicon-signal')
  clear(SOCKET_FAIL)
  g.blockchain.send('{"op":"addr_sub", "addr":"' + g.user.address + '"}')

g.blockchain.onerror =  ->
  $('#connection').addClass('glyphicon-exclamation-sign').removeClass('glyphicon-signal')
  g.blockchain = null
  fail(SOCKET_FAIL)

g.blockchain.onclose = ->
  $('#connection').addClass('glyphicon-exclamation-sign').removeClass('glyphicon-signal')
  g.blockchain = null
  fail(SOCKET_FAIL)
  listen()

g.blockchain.onmessage = (e) ->
  results = eval('(' + e.data + ')')
  amount = 0
  txid = results.x.hash

  return if txid == g.last
  g.last = txid

  $.each(results.x.out, (i, v) ->
    if (v.addr == g.user.address) 
      amount += v.value / 100000000
  )

  logTransaction(txid, amount)
```
